### ISSUE TITLE
Wrong field used for service title in placeholders?

### ISSUE THREAD

**Issue by hilburger** [ErHaWeb/klaro_consent_manager#4]
Hi Eric! 

I have just started to integrate Soundcloud via Guidos Soundcloud-Integration: https://github.com/ayacoo/ayacoo-soundcloud
It works pretty nicely so far (I am not ready yet), but I have an issue with the placeholder: 

It seems as if the name-field of a set up service is used for the {title}-label instead of the title-field:

![image](https://github.com/ErHaWeb/klaro_consent_manager/assets/2393228/8f389083-d064-4f40-9c43-4a2547ab3bab)

![image](https://github.com/ErHaWeb/klaro_consent_manager/assets/2393228/4e18de5b-0e71-4709-9eeb-d8c939a400ea)

So in the frontend I get 
  "Iframe Soundcloud" (field content is "iframe-soundcloud") 
instead of 
  "Soundcloud" (field content ist "Soundcloud")

**Comment by ErHaWeb** [comment]
Hi @hilburger, 

Please note the description of the `title` field in the backend:

> The title defined here is not mandatory and is intended for backend display only.

→ it says "for backend display only"

It is completely intentional that no translation-relevant information can be set in the backend, as multilingual installations can use the same Klaro configuration in this way. Translations originate 100% from XLIFF files.

In the case you mentioned, Klaro cannot find a suitable label and therefore creates a label itself based on the service identifier ("name").

So what is the correct XLIFF key for your service?

```
services.<YOUR_SERVICE_NAME>.title
```

However, I have just noticed that the text defined there is only used in the Consent Box but not in the contextual Consent.

I will correct this at the beginning of next week.

**Comment by hilburger** [comment]
Thank you and alright! 
So the last one seems to be the case in the contextual consent as the consent box looks alright in all languages:
 
![image](https://github.com/ErHaWeb/klaro_consent_manager/assets/2393228/1dead4e3-361a-4eda-9379-67cad9c6c740)

My site package's xlf file seems fine as it generally works. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
	<file source-language="en" datatype="plaintext" original="EXT:tnt_sitepackage_bs5/Resources/Private/Language/Klaro/locallang.xlf" date="2023-12-01T15:24:52Z" product-name="tnt_sitepackage_bs5">
		<header/>
		<body>
			<trans-unit id="purposes.media.title" resname="purposes.media.title">
				<source>Media</source>
			</trans-unit>
			<trans-unit id="purposes.media.description" resname="purposes.media.description">
				<source>Services related to stream video and music.</source>
			</trans-unit>
			<trans-unit id="services.iframe-soundcloud.title" resname="services.iframe-soundcloud.title">
				<source>Soundcloud</source>
			</trans-unit>
			<trans-unit id="services.iframe-soundcloud.description" resname="services.iframe-soundcloud.description">
				<source>The streaming service for musicians, we use their player for sound demos. </source>
			</trans-unit>
			<trans-unit id="save" resname="save">
				<source>Save</source>
			</trans-unit>
		</body>
	</file>
</xliff>
```

**Comment by ErHaWeb** [comment]
This was fixed with the latest release.
