### ISSUE TITLE
Highlander Question: There can be only one Klaro config which can't be deleted?

### ISSUE THREAD

**Issue by hilburger** [ErHaWeb/klaro_consent_manager#5]
By (bad) luck I have stumpled over the follwing effect and don't know how to solve it properly. 
Maybe it is easier to understand by showing the steps. 

The steps: 

1. Create a Klaro Configuration and at least one service on some subfolder page in the pagetree. 
2. Forget about the fact that you have created it (important ;-) )
3. After forgetting about the first config create a new one on the root page (you can use the same name to make things more funny).
4. Create more services if you like on root page.
5. Find out that the settings of your second config (remember you forgot about the other one) do nothing. 
6. Look around and finally find the old first config.
7. Think that it is best to delete the old one because you have set up what you need in the new one on the root page. 
8. So delete the old one.  
9. Find out that the new config still does not have any effect but this time there is no trace of Klaro in the FE anymore. 
10. In the DB set deleted value of the first old config from 1 to 0 and find it in the BE again. 
11. See that the cookie modal comes back again and all Klaro funcionality, too. 
Finally
12. Ask yourself how it comes that only the first config you ever created is used by the Klaro-Ext. 
And 
13. Wonder what would happen if you delete the first config also in the DB.

**Comment by ErHaWeb** [comment]
I haven't reproduced this problem step by step yet, but I have a question about what I've read so far: Could it be because the second Klaro configuration is not referenced via the site configuration? It only has an effect in this case. If the old Klaro configuration is still in effect after you reset its delete status, then, as I understand it, it's only because its uid was still stored in the site configuration.

**Comment by ErHaWeb** [comment]
Closed due to inactivity. If the problem persists, please open a new ticket.
